### PR TITLE
FIX Expose root package resources

### PR DESCRIPTION
**Pull request by dhensby**
This fix allows root packages (projects / modules that install their own deps for tests) to expose their own resources as well as those of their dependencies

### CODE REVIEW

**Comment by tractorcow** [comment]
I think in the future when we move to non-public BASE_PATH we may want to do this, but at this point in time it's premature optimisation. I would rather leave this feature out for the time being until we had a definite need for it.

**Comment by dhensby** [comment]
I've been reliably informed that there have already been requests by community members around how to get mysite files "exposed".

I think there's definitely value to having all public static assets in a canonical resource location

**Comment by tractorcow** [comment]
> I've been reliably informed that there have already been requests by community members around how to get mysite files "exposed".

They already are... I'd rather not imply there's a reason for concern if we don't shift these to resources.

> I think there's definitely value to having all public static assets in a canonical resource location

That's more error prone than a simple vendor/ -> resources/ mapping; Mysite isn't installed by composer, and thus is more likely to have a resource map missing.

I want to address this once we move to non-public webroot, but I would rather wait until then to set the convention, not pre-emptively, in case we need to switch the paths a second time.

**Comment by tractorcow** [comment]
When we move to non-public webroot, what we'll probably do is make `resources` the mirror of the public resources of webroot.

e.g.

```
vendor/silverstripe/admin/client/file.js -> resources/vendor/silverstripe/admin/client/file.js
mysite/script/file.js -> resources/mysite/script/file.js
```

Possible we could remove 'vendor' from the mapped name, but it could conflict with other non-vendor top level folders, so maybe it should be kept.

**Comment by dhensby** [comment]
> Mysite isn't installed by composer, and thus is more likely to have a resource map missing.

Sure, but if no `expose` data is set then nothing changes - this change just allows someone to set an `expose` in their project *if they want*.

Overall I'm not *that* bothered, but it just seems odd that we aren't consistent with this

**Comment by tractorcow** [comment]
Hi @dhensby we just had a chat about this issue in open sourcerers meeting; We will need some way to expose certain root resources to public, but we are also considering recommending users to commit files to `public/` folder directly. I think we'll probably use your soultion "as-is", but would like time to test and confirm it works with the new public folder system. :)

**Comment by dhensby** [comment]
Sure :)

**Comment by tractorcow** [comment]
Updated PR at https://github.com/silverstripe/vendor-plugin/pull/12

**Comment by tractorcow** [comment]
Replaced with https://github.com/silverstripe/vendor-plugin/pull/12

**Pull request closed without merging**
