### PR TITLE
API Remove configuration of _resources path

### PR DESCRIPTION
**Pull request by GuySartorelli**
**NOTE** This will need to be targetted at `2` once that branch has been created (see https://github.com/silverstripe/silverstripe-framework/issues/10349)

## BC breaking changes
- Removed `Library::DEFAULT_RESOURCES_DIR`
- Set `Library::RESOURCES_PATH` to explicitly be "_resources"
- Removed `Library::getResourcesDir()`

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10399

### CODE REVIEW

**Comment by michalkleiner** [comment]
Why would we remove the configurability of this and not just change the default?

**Comment by GuySartorelli** [comment]
That's 2hat the issue is for, but I realised that after doing the work. The configuration feels a bit like tech debt to me but have asked for clarification of the intent.

**Comment by michalkleiner** [comment]
I reckon once it was made configurable it feels wrong to force users into something opinionated again, so I would vote for changing the default to `_resources` so it's consistent with what some other modules had configured, but leave it configurable so that devs can still leverage that in project code if they wanted to. I imagine not everyone is using _resources, might be using something custom and have other systems/URLs etc depending on it.

**Comment by GuySartorelli** [comment]
Closed in favor of https://github.com/silverstripe/vendor-plugin/pull/57

**Pull request closed without merging**
